package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class KlientManager {
	private Connection connection;
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	private String createTableKlient = "CREATE TABLE Klient(id_klient long GENERATED BY DEFAULT AS IDENTITY, imie varchar(50), nazwisko varchar(100), numertelefonu long)";
	
	private PreparedStatement DodajKlienta;
	private PreparedStatement UsunKlienta;
	private PreparedStatement UsunKlientow;
	private PreparedStatement EdytujKlienta;
	private PreparedStatement PobierzKlientow;
}
